import type { VendorTheme, Vendor } from '../types';

export const VENDOR_THEMES: Record<Vendor, VendorTheme> = {
  huawei: {
    vendor: 'huawei',
    label: '华为 Huawei',
    brandColor: '#cf0a2c',
    interfacePrefixes: {
      ethernet: 'GigabitEthernet',
      serial: 'Serial',
      fiber: 'XGigabitEthernet',
      management: 'MEth',
      vlan: 'Vlanif',
      loopback: 'LoopBack',
    },
    cli: {
      commentChar: '#',
      promptEndDelimiter: ']',
      systemViewCommand: 'system-view',
      enableCommand: 'system-view',
      displayCommand: 'display',
      ospfKeyword: 'ospf',
      vlanKeyword: 'vlan',
      defaultRouteKeyword: 'ip route-static',
    },
    nodeStyles: {
      router: '#cf0a2c',
      switch: '#0a6ecf',
      firewall: '#e8781a',
      ac: '#6b2fa0',
      ap: '#0a8f5c',
      'access-controller': '#6b2fa0',
      'access-point': '#0a8f5c',
      pc: '#4b5563',
      server: '#1d4ed8',
      cloud: '#0891b2',
    },
  },
  h3c: {
    vendor: 'h3c',
    label: '华三 H3C',
    brandColor: '#0058b0',
    interfacePrefixes: {
      ethernet: 'GigabitEthernet',
      serial: 'Serial',
      fiber: 'Ten-GigabitEthernet',
      management: 'M-GigabitEthernet',
      vlan: 'Vlan-interface',
      loopback: 'LoopBack',
    },
    cli: {
      commentChar: '#',
      promptEndDelimiter: ']',
      systemViewCommand: 'system-view',
      enableCommand: 'system-view',
      displayCommand: 'display',
      ospfKeyword: 'ospf',
      vlanKeyword: 'vlan',
      defaultRouteKeyword: 'ip route-static',
    },
    nodeStyles: {
      router: '#0058b0',
      switch: '#009fda',
      firewall: '#f26322',
      ac: '#7b3fa3',
      ap: '#00a86b',
      'access-controller': '#7b3fa3',
      'access-point': '#00a86b',
      pc: '#4b5563',
      server: '#2563eb',
      cloud: '#0e7490',
    },
  },
  cisco: {
    vendor: 'cisco',
    label: '思科 Cisco',
    brandColor: '#049fd9',
    interfacePrefixes: {
      ethernet: 'GigabitEthernet',
      serial: 'Serial',
      fiber: 'TenGigabitEthernet',
      management: 'Management',
      vlan: 'Vlan',
      loopback: 'Loopback',
    },
    cli: {
      commentChar: '!',
      promptEndDelimiter: ')',
      systemViewCommand: 'configure terminal',
      enableCommand: 'enable',
      displayCommand: 'show',
      ospfKeyword: 'ospf',
      vlanKeyword: 'vlan',
      defaultRouteKeyword: 'ip route',
    },
    nodeStyles: {
      router: '#049fd9',
      switch: '#00882c',
      firewall: '#e84d0e',
      ac: '#9b30ff',
      ap: '#2eb82e',
      'access-controller': '#9b30ff',
      'access-point': '#2eb82e',
      pc: '#4b5563',
      server: '#1d4ed8',
      cloud: '#0891b2',
    },
  },
  ruijie: {
    vendor: 'ruijie',
    label: '锐捷 Ruijie',
    brandColor: '#e60012',
    interfacePrefixes: {
      ethernet: 'GigabitEthernet',
      serial: 'Serial',
      fiber: 'TenGigabitEthernet',
      management: 'Management',
      vlan: 'Vlan',
      loopback: 'Loopback',
    },
    cli: {
      commentChar: '!',
      promptEndDelimiter: ')',
      systemViewCommand: 'configure terminal',
      enableCommand: 'enable',
      displayCommand: 'show',
      ospfKeyword: 'router ospf',
      vlanKeyword: 'vlan',
      defaultRouteKeyword: 'ip route',
    },
    nodeStyles: {
      router: '#e60012',
      switch: '#0066b3',
      firewall: '#f58220',
      ac: '#5c2d91',
      ap: '#009a44',
      'access-controller': '#5c2d91',
      'access-point': '#009a44',
      pc: '#4b5563',
      server: '#1d4ed8',
      cloud: '#0891b2',
    },
  },
};
